"""
PDF clinical report generation using ReportLab.
Stores reports in /tmp/reports/<token>.pdf (expires in 24 h).
"""
import os, io, base64, datetime
from PIL import Image

REPORT_DIR = "/tmp/reports"
os.makedirs(REPORT_DIR, exist_ok=True)


def build_pdf(request_id, severity, detections, images, patient_name=None, advanced=None) -> str:
    """Build PDF and return the report token (= request_id)."""
    try:
        from reportlab.lib.pagesizes import A4
        from reportlab.lib import colors
        from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle, Image as RLImage
        from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
        from reportlab.lib.units import cm

        path  = os.path.join(REPORT_DIR, f"{request_id}.pdf")
        doc   = SimpleDocTemplate(path, pagesize=A4)
        styles = getSampleStyleSheet()
        story  = []

        title_style = ParagraphStyle("Title", parent=styles["Heading1"],
                                     fontSize=20, textColor=colors.HexColor("#e8614a"))
        story.append(Paragraph("AlveolaAI Clinical Report", title_style))
        story.append(Spacer(1, 0.5 * cm))

        # Patient info
        info_data = [
            ["Request ID:",   request_id],
            ["Patient:",      patient_name or "Anonymous"],
            ["Timestamp:",    datetime.datetime.utcnow().strftime("%Y-%m-%d %H:%M UTC")],
            ["Severity:",     severity.label],
            ["Opacity:",      f"{severity.opacity_pct}%"],
            ["Confidence:",   f"{round(severity.confidence * 100)}%"],
        ]
        t = Table(info_data, colWidths=[4 * cm, 12 * cm])
        t.setStyle(TableStyle([
            ("FONTNAME",    (0, 0), (-1, -1), "Helvetica"),
            ("FONTSIZE",    (0, 0), (-1, -1), 10),
            ("TEXTCOLOR",   (0, 0), (0, -1),  colors.grey),
            ("ROWBACKGROUNDS", (0, 0), (-1, -1), [colors.white, colors.HexColor("#f8f9fa")]),
            ("BOX",         (0, 0), (-1, -1),  0.5, colors.lightgrey),
            ("INNERGRID",   (0, 0), (-1, -1),  0.25, colors.lightgrey),
        ]))
        story.append(t)
        story.append(Spacer(1, 0.8 * cm))

        # Detections table
        if detections:
            story.append(Paragraph("Detected Opacity Regions", styles["Heading2"]))
            det_data = [["Region", "BBox [x,y,w,h]", "Confidence", "Area (px)"]]
            for d in detections:
                det_data.append([
                    f"Region {d.id}",
                    str([round(v, 1) for v in d.bbox]),
                    f"{round(d.confidence * 100, 1)}%",
                    f"{d.area_px:,}",
                ])
            dt = Table(det_data, colWidths=[3*cm, 7*cm, 4*cm, 3*cm])
            dt.setStyle(TableStyle([
                ("BACKGROUND",  (0, 0), (-1, 0),  colors.HexColor("#e8614a")),
                ("TEXTCOLOR",   (0, 0), (-1, 0),  colors.white),
                ("FONTNAME",    (0, 0), (-1, 0),  "Helvetica-Bold"),
                ("FONTSIZE",    (0, 0), (-1, -1), 9),
                ("ROWBACKGROUNDS", (0, 1), (-1, -1), [colors.white, colors.HexColor("#fff5f3")]),
                ("INNERGRID",   (0, 0), (-1, -1),  0.25, colors.lightgrey),
                ("BOX",         (0, 0), (-1, -1),  0.5, colors.lightgrey),
            ]))
            story.append(dt)
            story.append(Spacer(1, 0.5 * cm))

        # Thumbnail
        try:
            thumb_bytes = base64.b64decode(images.thumbnail)
            thumb_img   = RLImage(io.BytesIO(thumb_bytes), width=6*cm, height=6*cm)
            story.append(Paragraph("Radiograph Thumbnail", styles["Heading2"]))
            story.append(thumb_img)
        except Exception:
            pass

        story.append(Spacer(1, 1 * cm))
        disclaimer = ("This report is generated by AlveolaAI and is intended to assist "
                      "qualified healthcare professionals only. It is not a substitute for "
                      "clinical diagnosis. Always consult a licensed physician.")
        story.append(Paragraph(disclaimer, ParagraphStyle("Disclaimer", fontSize=8, textColor=colors.grey)))

        doc.build(story)
        return request_id

    except ImportError:
        # ReportLab not installed — return token without generating file
        return request_id
